"""empty message

Revision ID: 97913352ec80
Revises: 
Create Date: 2023-08-05 20:17:10.496377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97913352ec80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('questionstesting')
    # op.drop_table('questions')
    # op.drop_table('cues')
    # op.drop_table('clues')
    # op.drop_table('contestants')
    # op.drop_table('games')
    # op.drop_table('categories')
    # op.drop_table('seasons')
    op.add_column('user_answer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('user_answer', sa.Column('question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answer', 'question_id')
    op.drop_column('user_answer', 'user_id')
    op.create_table('seasons',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_games', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('categories',
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clue_count', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episode_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('air_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contestant1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contestant2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contestant3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score3', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('contestants',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('games_played', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_winnings', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('clues',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_double', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('round', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categorytitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('clue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('cues',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_double', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('round', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categorytitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('clue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('questions',
    sa.Column('questionid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question', sa.VARCHAR(length=650), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('airdate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoryid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gameid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categorytitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cluescount', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('questionstesting',
    sa.Column('questionid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
